version: '3'

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - sqlData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=test

  zoo:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    image: skadimisetty/zk
    ports:
      - "2181:2181"
    #volumes:
      #- zooData:

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    image: skadimisetty/kafka
    ports:
      - "9092:9092"
    environment:
         #brokerId: kafka-1
         zkQuorum: zoo:2181
    depends_on:
      - zoo
    volumes:
      - kafkaLog:/kafka/kafka_2.12-0.10.2.1/log
    #  - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    image: cassandra
    volumes:
      - cassandraData:/var/lib/cassandra

  nifi:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    image: skadimisetty/nifi
    ports:
      - "9000:8080"
    depends_on:
      - zoo
      - kafka
      - mysql
      - cassandra

  demo-service:
    build:
      context: ./demo-java/spring-data-demo
      dockerfile: dockerfile
    image: skadimisetty/java-rest-ws
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always



volumes:
  sqlData:
  cassandraData:
  kafkaLog:
